- name: Add the user 'hadoop'
  user:
    name: hadoop
    password: "{{ 'password' | password_hash('sha512') }}"
    comment: hadoop
    shell: /bin/bash

- name: Create a SSH key for user hadoop in ~hadoop/.ssh/id_rsa
  user:
    name: hadoop
    generate_ssh_key: yes

- name: Create file - authorized_keys
  shell: cat /home/hadoop/.ssh/id_rsa.pub > /home/hadoop/.ssh/authorized_keys
  args:
    executable: /bin/bash

- name: Create known_hosts - localhost
  become_user: hadoop
  shell: ssh-keyscan -H localhost >> /home/hadoop/.ssh/known_hosts

- name: Create known_hosts - hadoop-master
  become_user: hadoop
  shell: ssh-keyscan -H hadoop-master >> /home/hadoop/.ssh/known_hosts
